import { afterEach, describe, expect, it } from "vitest";
import { listQueryAccountIds, resolveQueryAccount } from "./config.js";

afterEach(() => {
  delete process.env.QUERY_OPENCLAW_TOKEN;
  delete process.env.QUERY_AGENT_ACTIVITY_MODE;
});

describe("Query account configuration", () => {
  it("accepts the complete connection URL generated by Query", () => {
    const account = resolveQueryAccount(
      {
        channels: {
          query: {
            url: "wss://query.test/ws/openclaw-agent/42/?token=bundle-secret",
          },
        },
      } as never,
    );
    expect(account.configured).toBe(true);
    expect(account.token).toBe("bundle-secret");
  });

  it("prefers explicit and environment tokens over the URL token", () => {
    process.env.QUERY_OPENCLAW_TOKEN = "environment-secret";
    const fromEnvironment = resolveQueryAccount({
      channels: { query: { url: "wss://query.test/ws/?token=url-secret" } },
    } as never);
    expect(fromEnvironment.token).toBe("environment-secret");

    const explicit = resolveQueryAccount({
      channels: {
        query: { url: "wss://query.test/ws/?token=url-secret", token: "explicit-secret" },
      },
    } as never);
    expect(explicit.token).toBe("explicit-secret");
  });

  it("accepts an optional websocket origin", () => {
    const account = resolveQueryAccount({
      channels: {
        query: {
          url: "wss://query.test/ws/?token=url-secret",
          origin: "https://us.itsquery.com",
        },
      },
    } as never);
    expect(account.origin).toBe("https://us.itsquery.com");
  });

  it("lists and resolves multiple Query accounts", () => {
    const cfg = {
      channels: {
        query: {
          enabled: true,
          origin: "https://us.itsquery.com",
          accounts: {
            query: {
              url: "wss://apius.itsquery.com/ws/openclaw-agent/3/?token=query-secret",
            },
            "director-asocapitales": {
              url: "wss://apiasocapitales.itsquery.com/ws/openclaw-agent/1/?token=director-secret",
              stateFile: "/tmp/director-cache.json",
            },
          },
        },
      },
    } as never;

    expect(listQueryAccountIds(cfg)).toEqual(["query", "director-asocapitales"]);
    expect(resolveQueryAccount(cfg, "query")).toMatchObject({
      accountId: "query",
      configured: true,
      token: "query-secret",
      origin: "https://us.itsquery.com",
    });
    expect(resolveQueryAccount(cfg, "director-asocapitales")).toMatchObject({
      accountId: "director-asocapitales",
      configured: true,
      token: "director-secret",
      origin: "https://us.itsquery.com",
      stateFile: "/tmp/director-cache.json",
    });
  });
});

describe("modo de actividad de la cuenta", () => {
  it("usa smart cuando nadie dice otra cosa", () => {
    const account = resolveQueryAccount({
      channels: { query: { url: "wss://query.test/ws/?token=t" } },
    } as never);
    expect(account.activityMode).toBe("smart");
  });

  it("respeta el modo del canal y el de una cuenta concreta", () => {
    const cfg = {
      channels: {
        query: {
          url: "wss://query.test/ws/?token=t",
          activityMode: "lite",
          accounts: {
            soporte: { url: "wss://query.test/ws/?token=t", activityMode: "verbose" },
            ventas: { url: "wss://query.test/ws/?token=t" },
          },
        },
      },
    } as never;
    expect(resolveQueryAccount(cfg, "soporte").activityMode).toBe("verbose");
    // La cuenta sin modo propio hereda el del canal.
    expect(resolveQueryAccount(cfg, "ventas").activityMode).toBe("lite");
  });

  it("cae al entorno y descarta un modo desconocido", () => {
    process.env.QUERY_AGENT_ACTIVITY_MODE = "debug-internal";
    const heredado = resolveQueryAccount({
      channels: { query: { url: "wss://query.test/ws/?token=t" } },
    } as never);
    expect(heredado.activityMode).toBe("debug-internal");

    const invalido = resolveQueryAccount({
      channels: { query: { url: "wss://query.test/ws/?token=t", activityMode: "ruidoso" } },
    } as never);
    expect(invalido.activityMode).toBe("debug-internal");
  });
});
