import { afterEach, describe, expect, it } from "vitest";
import { resolveQueryAccount } from "./config.js";

afterEach(() => {
  delete process.env.QUERY_OPENCLAW_TOKEN;
});

describe("Query account configuration", () => {
  it("accepts the complete connection URL generated by Query", () => {
    const account = resolveQueryAccount(
      {
        channels: {
          query: {
            url: "wss://query.test/ws/openclaw-agent/42/?token=bundle-secret",
          },
        },
      } as never,
    );
    expect(account.configured).toBe(true);
    expect(account.token).toBe("bundle-secret");
  });

  it("prefers explicit and environment tokens over the URL token", () => {
    process.env.QUERY_OPENCLAW_TOKEN = "environment-secret";
    const fromEnvironment = resolveQueryAccount({
      channels: { query: { url: "wss://query.test/ws/?token=url-secret" } },
    } as never);
    expect(fromEnvironment.token).toBe("environment-secret");

    const explicit = resolveQueryAccount({
      channels: {
        query: { url: "wss://query.test/ws/?token=url-secret", token: "explicit-secret" },
      },
    } as never);
    expect(explicit.token).toBe("explicit-secret");
  });

  it("accepts an optional websocket origin", () => {
    const account = resolveQueryAccount({
      channels: {
        query: {
          url: "wss://query.test/ws/?token=url-secret",
          origin: "https://us.itsquery.com",
        },
      },
    } as never);
    expect(account.origin).toBe("https://us.itsquery.com");
  });
});
